service:
  name: bira

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: 
      forceExclude:
        - aws-sdk
  serverless-offline:
    httpPort: 3200
  serverless-offline-ssm:
    stages:
      - next
      - uat
      - prod


package:
  exclude:
  - .vscode/**
  - .tests/**

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  apiGateway:
    # accepted binary type for file uploads
    binaryMediaTypes:
      - 'multipart/form-data'

functions:
  uploadFile:
      handler: handler.uploadFile
      events:
        - http:
            method: post
            path: upload
            cors: true
  parseResume:
      handler: handler.parseResume
      events:
        - http:
            method: post
            path: parse_resume
            cors: true 
resources:
  Resources:
    MyServerlessExampleBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bira-bucket

    # define a policy for an existing role
    UploadFilePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: UploadObjects
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: LambdaPutObjects
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectTagging
              Resource: 
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: MyServerlessExampleBucket
                    - "/*"
        Roles:
          - bira-dev-us-east-1-lambdaRole 
