service: serverless-example

provider:
  name: aws
  runtime: nodejs12.x
  profile: transkribo
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  apiGateway:
    # accepted binary type for file uploads
    binaryMediaTypes:
      - 'multipart/form-data'

package:
  exclude:
    - ./*.md
    - ./*.js
    - ./**/*.ts
    - ./**.json
    - ./__tests__/**
  include:
    - build/**

functions:
  # option 1: sync upload
  uploadFile:
    handler: build.uploadFile
    events:
      - http:
          method: post
          path: upload
          cors: true
  # option 2: pre-signed URL
  createUploadUrl:
    handler: build.createUploadUrl
    events: 
      - http: 
          method: post
          path: createUploadUrl
          cors: true
  # option 3: post-signed URL
  createPostUploadUrl:
    handler: build.createPostUploadUrl
    events: 
      - http: 
          method: post
          path: createPostUploadUrl
          cors: true

resources:
  Resources:
    MyServerlessExampleBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-example-bucket

    # define a policy for an existing role
    UploadFilePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: UploadObjects
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: LambdaPutObjects
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectTagging
              Resource: 
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: MyServerlessExampleBucket
                    - "/*"
        Roles:
          - serverless-example-dev-us-east-1-lambdaRole 